dist: xenial
language: rust
sudo: required

before_install:
  - rustup self update

install:
  - sudo apt -qq update
  - sudo apt -qq install libgpgme11-dev wget unzip
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip
  - sudo mv bin/protoc /usr/local/bin/protoc
  - cargo update

script:
  - cargo test -- --test-threads=1

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo